# Generated by Django 3.1.7 on 2021-04-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128, unique=True)),
                ('desc', models.CharField(db_index=True, max_length=512)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('count', models.PositiveSmallIntegerField()),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('brand', models.ManyToManyField(blank=True, related_name='items', to='shop.Brand')),
                ('category', models.ManyToManyField(blank=True, related_name='items', to='shop.Category')),
                ('country', models.ManyToManyField(blank=True, related_name='items', to='shop.Country')),
            ],
        ),
    ]
