# Generated by Django 3.1.7 on 2021-05-17 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_item_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='desc',
            field=models.CharField(db_index=True, max_length=512, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='desc',
            field=models.CharField(db_index=True, max_length=512, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='item',
            name='brand',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.brand', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='items', to='shop.Category', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='item',
            name='count',
            field=models.PositiveSmallIntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='item',
            name='country',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.country', verbose_name='Страна производитель'),
        ),
        migrations.AlterField(
            model_name='item',
            name='desc',
            field=models.CharField(db_index=True, max_length=512, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='item',
            name='img',
            field=models.ImageField(blank=True, upload_to='images/items', verbose_name='Фото товара'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(db_index=True, max_length=128, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена'),
        ),
    ]
