# Generated by Django 3.1.7 on 2021-05-29 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_item_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-updated_at']},
        ),
    ]
