# Generated by Django 3.1.7 on 2021-04-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField()),
                ('item_id', models.PositiveIntegerField()),
                ('count', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
